# Generated by Django 4.0 on 2022-03-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='Time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
