# Generated by Django 4.0 on 2022-03-10 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_contactus_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='Time',
            new_name='Timenow',
        ),
    ]
